spring:
    datasource:
        url: ${DB_URL:jdbc:postgresql://localhost:5435/openmind_db}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:root}
        driver-class-name: org.postgresql.Driver
    freemarker:
        suffix: ".ftl"
    flyway:
        out-of-order: true
        baseline-on-migrate: true

user:
    mininal_age: 16